#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2014 Martin Ueding <martin-ueding.de>
# Licensed under The GNU Public License Version 2 (or later)

import argparse
import subprocess

def string(ssid, psk):
    s = 'WIFI:S:{ssid};T:WPA;P:{psk};;'.format(
        ssid=ssid,
        psk=psk,
    )
    return s

def main():
    options = _parse_args()

    s = string(options.SSID, options.PSK)

    subprocess.check_call([
        'qrencode',
        '-l', 'H',
        '-s', '5',
        '-o', options.outfile,
        s,
    ])

def _parse_args():
    '''
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    '''
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('SSID')
    parser.add_argument('PSK')
    parser.add_argument('outfile')
    options = parser.parse_args()

    return options

if __name__ == '__main__':
    main()
